let propertiesArrays = [["ecl", "cid", "iyr", "hgt", "eyr", "pid", "byr", "hcl"],
["byr", "hcl", "ecl", "cid", "eyr", "pid", "iyr", "hgt"],
["byr", "eyr", "hgt", "cid", "iyr", "ecl", "hcl", "pid"],
["eyr", "ecl", "iyr", "byr", "pid", "hgt", "hcl"],
["pid", "hcl", "hgt", "ecl", "eyr", "byr", "iyr"],
["byr", "hgt", "hcl", "iyr", "ecl", "pid", "eyr"],
["hgt", "ecl", "byr", "pid", "iyr", "hcl", "eyr"],
["hcl", "eyr", "ecl", "byr", "hgt", "iyr", "pid"],
["pid", "iyr", "hgt", "cid", "hcl", "eyr", "byr", "ecl"],
["hgt", "hcl", "ecl", "byr", "pid", "eyr", "iyr"],
["pid", "hcl", "ecl", "eyr", "byr", "hgt", "iyr"],
["hcl", "ecl", "eyr", "iyr", "pid", "cid", "byr", "hgt"],
["hcl", "ecl", "byr", "iyr", "eyr", "cid", "pid", "hgt"],
["pid", "eyr", "hcl", "iyr", "hgt", "byr"],
["hgt", "byr", "pid", "hcl", "ecl", "iyr", "cid", "eyr"],
["pid", "iyr", "hgt", "ecl", "eyr", "hcl", "cid"],
["iyr", "eyr", "hcl", "pid", "byr", "ecl"],
["hcl", "iyr", "pid", "byr", "ecl", "eyr", "hgt"],
["hgt", "cid", "pid", "iyr", "ecl", "hcl", "eyr"],
["hcl", "cid", "hgt", "byr", "pid", "eyr", "iyr", "ecl"],
["byr", "hcl", "eyr", "hgt", "pid", "iyr", "ecl"],
["eyr", "byr", "ecl", "cid", "hgt", "pid", "iyr", "hcl"],
["ecl", "cid", "hcl", "eyr", "iyr", "byr", "pid", "hgt"],
["pid", "eyr", "hcl", "cid", "iyr", "hgt", "byr", "ecl"],
["hgt", "ecl", "byr", "iyr", "hcl", "eyr"],
["hgt", "hcl", "byr", "pid", "iyr", "eyr"],
["iyr", "ecl", "eyr", "hgt", "byr", "pid", "hcl"],
["pid", "hcl", "eyr", "ecl", "byr", "iyr"],
["eyr", "byr", "hcl", "ecl", "pid", "hgt", "cid", "iyr"],
["cid", "pid", "eyr", "hgt", "byr", "iyr", "ecl"],
["eyr", "pid", "hgt", "iyr", "ecl", "hcl", "byr"],
["byr", "pid", "hcl", "ecl", "hgt", "eyr", "iyr"],
["pid", "hgt", "byr", "ecl", "hcl", "iyr", "eyr"],
["iyr", "eyr", "ecl", "hgt", "hcl", "pid", "byr"],
["hgt", "byr", "iyr", "pid", "ecl", "cid", "eyr", "hcl"],
["hcl", "pid", "iyr", "ecl", "byr", "hgt", "eyr", "cid"],
["hcl", "iyr", "ecl", "eyr", "hgt", "byr", "pid"],
["eyr", "ecl", "hgt", "byr", "cid", "hcl", "iyr", "pid"],
["hcl", "pid", "iyr", "byr", "ecl", "eyr", "hgt"],
["hgt", "iyr", "ecl", "byr", "eyr", "pid", "hcl"],
["cid", "pid", "ecl", "hcl", "eyr", "byr", "hgt", "iyr"],
["hgt", "pid", "cid", "byr", "ecl", "eyr", "hcl", "iyr"],
["cid", "hcl", "ecl", "iyr", "eyr", "hgt", "byr"],
["pid", "byr", "hcl", "ecl", "iyr", "hgt", "cid", "eyr"],
["pid", "eyr", "hgt", "hcl", "iyr", "byr", "ecl"],
["iyr", "hgt", "hcl", "eyr", "pid", "ecl", "byr"],
["pid", "byr", "ecl", "iyr", "cid", "hcl", "hgt"],
["pid", "hcl", "iyr", "eyr", "hgt", "byr", "ecl"],
["pid", "byr", "hgt", "iyr", "eyr"],
["eyr", "hgt", "cid", "iyr", "pid", "ecl", "byr", "hcl"],
["eyr", "ecl", "iyr", "hcl", "byr", "hgt", "pid"],
["eyr", "iyr", "byr", "ecl", "hgt", "hcl", "pid"],
["iyr", "byr", "eyr", "hgt", "hcl", "ecl"],
["cid", "byr", "eyr", "hgt", "pid", "hcl", "iyr", "ecl"],
["eyr", "pid", "ecl", "iyr", "hcl", "byr", "hgt"],
["eyr", "hgt", "ecl", "hcl", "pid", "byr", "iyr"],
["iyr", "cid", "ecl", "hcl", "hgt", "pid", "eyr"],
["ecl", "hcl", "byr", "pid", "iyr", "cid", "hgt", "eyr"],
["pid", "hgt", "hcl", "cid", "byr", "ecl", "iyr", "eyr"],
["pid", "hcl", "hgt", "iyr", "eyr", "byr", "ecl"],
["ecl", "hcl", "pid", "iyr", "byr", "cid", "eyr"],
["iyr", "byr", "hgt", "hcl", "ecl", "eyr"],
["iyr", "byr", "ecl", "pid", "hcl", "hgt", "cid", "eyr"],
["pid", "eyr", "iyr", "hgt", "hcl", "byr", "ecl"],
["pid", "ecl", "byr", "iyr", "hcl", "hgt", "cid", "eyr"],
["byr", "hcl", "iyr", "pid", "hgt", "ecl", "eyr", "cid"],
["eyr", "hcl", "ecl", "iyr", "pid", "hgt", "byr"],
["cid", "iyr", "pid", "hgt", "ecl", "byr", "eyr", "hcl"],
["iyr", "hgt", "byr", "ecl", "cid", "eyr", "pid", "hcl"],
["ecl", "hcl", "pid", "eyr", "hgt", "cid", "iyr"],
["pid", "hgt", "ecl", "eyr", "byr", "iyr", "hcl"],
["eyr", "byr", "hgt", "ecl", "cid", "pid", "hcl", "iyr"],
["eyr", "hgt", "hcl", "iyr", "byr", "pid", "ecl", "cid"],
["pid", "iyr", "byr", "hgt", "eyr", "hcl", "cid", "ecl"],
["hgt", "pid", "iyr", "ecl", "byr", "eyr", "hcl"],
["hgt", "hcl", "byr", "ecl", "iyr", "cid", "eyr", "pid"],
["byr", "pid", "eyr", "hcl", "hgt", "iyr"],
["pid", "hgt", "iyr", "ecl", "hcl", "eyr", "cid", "byr"],
["hcl", "hgt", "cid", "ecl", "eyr", "pid", "byr", "iyr"],
["eyr", "byr", "pid", "cid", "hcl", "iyr", "ecl", "hgt"],
["ecl", "iyr", "hgt", "cid", "pid", "byr"],
["ecl", "iyr", "byr", "eyr", "hgt", "cid", "pid", "hcl"],
["iyr", "pid", "hcl", "byr", "ecl", "cid", "eyr", "hgt"],
["hcl", "byr", "ecl", "hgt", "iyr", "cid", "pid", "eyr"],
["iyr", "cid", "hgt", "hcl", "eyr", "pid", "ecl", "byr"],
["hgt", "cid", "pid", "hcl", "eyr", "ecl", "byr"],
["pid", "eyr", "hcl", "hgt", "ecl", "iyr", "byr"],
["ecl", "byr", "pid", "iyr", "hcl", "eyr", "hgt"],
["hcl", "pid", "ecl", "eyr", "cid", "iyr"],
["ecl", "pid", "eyr", "byr", "iyr", "hcl"],
["byr", "cid", "eyr", "pid", "iyr", "hcl", "ecl"],
["iyr", "hcl", "byr", "pid", "cid", "hgt", "eyr", "ecl"],
["pid", "iyr", "hcl", "eyr", "ecl", "hgt", "byr"],
["pid", "iyr", "eyr", "hcl", "ecl", "byr", "cid", "hgt"],
["ecl", "byr", "hgt", "iyr", "pid", "cid", "hcl", "eyr"],
["hcl", "ecl", "hgt", "eyr", "pid", "byr", "iyr"],
["hgt", "cid", "ecl", "hcl", "iyr", "eyr", "pid", "byr"],
["hcl", "cid", "eyr", "ecl", "hgt", "byr", "iyr", "pid"],
["byr", "eyr", "ecl", "pid", "hgt", "hcl"],
["hgt", "hcl", "cid", "eyr", "byr", "ecl", "pid", "iyr"],
["hcl", "pid", "ecl", "eyr", "hgt", "byr", "iyr"],
["ecl", "byr", "hcl", "eyr", "pid", "iyr", "hgt", "cid"],
["hcl", "iyr", "pid", "byr", "hgt", "eyr", "ecl"],
["cid", "byr", "hcl", "eyr", "iyr", "hgt", "pid"],
["byr", "eyr", "hcl", "ecl", "pid", "iyr", "hgt"],
["iyr", "cid", "eyr", "ecl", "pid", "hcl", "hgt", "byr"],
["pid", "ecl", "hgt", "iyr", "hcl", "eyr", "byr"],
["ecl", "iyr", "pid", "eyr", "hgt", "hcl", "byr"],
["hgt", "hcl", "byr", "ecl", "iyr", "eyr", "cid", "pid"],
["ecl", "hgt", "pid", "byr", "eyr", "iyr", "hcl"],
["pid", "cid", "iyr", "byr", "hgt", "hcl", "ecl", "eyr"],
["hgt", "ecl", "byr", "pid", "eyr", "hcl", "iyr"],
["ecl", "iyr", "hgt", "hcl", "byr", "pid", "eyr", "cid"],
["ecl", "hgt", "iyr", "cid", "hcl", "eyr", "byr", "pid"],
["ecl", "eyr", "pid", "byr", "cid", "hcl", "hgt", "iyr"],
["pid", "hgt", "iyr", "hcl", "byr", "cid", "eyr", "ecl"],
["ecl", "eyr", "pid", "byr", "cid", "hcl"],
["eyr", "byr", "iyr", "pid", "ecl", "hgt", "hcl"],
["hcl", "ecl", "pid", "byr", "eyr", "hgt", "iyr"],
["hgt", "eyr", "byr", "ecl", "hcl", "pid", "iyr", "cid"],
["cid", "hcl", "pid", "byr", "hgt", "eyr", "ecl", "iyr"],
["iyr", "eyr", "ecl", "hcl", "pid", "cid", "hgt", "byr"],
["hcl", "hgt", "iyr", "byr", "pid", "ecl", "eyr"],
["byr", "hgt", "eyr", "pid", "iyr", "ecl", "hcl"],
["iyr", "ecl", "eyr", "pid", "hgt", "byr", "hcl"],
["byr", "hcl", "eyr", "ecl", "pid", "hgt", "iyr", "cid"],
["ecl", "hgt", "iyr", "pid", "cid", "hcl", "eyr", "byr"],
["pid", "cid", "byr", "iyr", "hgt", "eyr"],
["pid", "ecl", "iyr", "byr", "hgt", "eyr"],
["pid", "iyr", "byr", "eyr", "ecl", "hcl", "hgt"],
["ecl", "byr", "cid", "iyr", "hcl", "eyr", "pid", "hgt"],
["hgt", "iyr", "eyr", "ecl", "pid", "hcl", "byr"],
["byr", "eyr", "pid", "iyr", "hcl", "hgt", "cid", "ecl"],
["pid", "hcl", "eyr", "byr", "ecl", "hgt", "iyr"],
["iyr", "byr", "hcl", "eyr", "hgt", "ecl"],
["ecl", "iyr", "eyr", "pid", "byr", "hcl", "cid", "hgt"],
["pid", "ecl", "hcl", "byr", "eyr", "hgt", "iyr"],
["eyr", "hgt", "hcl", "pid", "ecl", "byr", "iyr"],
["pid", "eyr", "ecl", "hcl", "hgt", "byr", "cid", "iyr"],
["hcl", "eyr", "pid", "hgt", "ecl", "iyr", "byr"],
["hcl", "pid", "hgt", "eyr", "ecl", "cid", "byr"],
["pid", "cid", "hgt", "hcl", "ecl", "iyr", "eyr"],
["pid", "hcl", "iyr", "byr", "cid", "eyr", "ecl", "hgt"],
["pid", "hcl", "hgt", "ecl", "eyr", "byr", "iyr"],
["hgt", "eyr", "ecl", "hcl", "byr", "pid", "iyr"],
["eyr", "byr", "cid", "ecl", "pid", "hgt", "hcl", "iyr"],
["byr", "iyr", "hgt", "eyr", "pid", "hcl", "cid", "ecl"],
["iyr", "ecl", "pid", "eyr", "hgt", "byr", "cid", "hcl"],
["cid", "byr", "hcl", "eyr", "hgt", "pid", "iyr", "ecl"],
["hgt", "ecl", "byr", "pid", "hcl", "iyr"],
["pid", "ecl", "byr", "hgt", "hcl", "iyr"],
["pid", "hcl", "cid", "hgt", "byr", "ecl", "eyr"],
["ecl", "byr", "cid", "pid", "hcl", "iyr", "hgt", "eyr"],
["byr", "hgt", "cid", "eyr", "ecl", "hcl", "iyr"],
["eyr", "ecl", "pid", "byr", "iyr", "hgt", "hcl"],
["byr", "eyr", "iyr", "ecl", "hcl", "pid", "hgt"],
["ecl", "iyr", "byr", "cid", "hcl", "pid", "hgt", "eyr"],
["pid", "iyr", "ecl", "eyr", "hcl", "hgt", "byr"],
["byr", "iyr", "ecl", "hcl", "hgt", "eyr", "pid"],
["cid", "hgt", "pid", "iyr", "ecl", "byr", "eyr", "hcl"],
["cid", "hgt", "hcl", "iyr", "ecl", "eyr", "byr", "pid"],
["hcl", "pid", "eyr", "iyr", "hgt", "byr", "ecl"],
["ecl", "hcl", "byr", "eyr", "iyr", "hgt", "pid"],
["hcl", "byr", "hgt", "iyr", "pid", "eyr"],
["hgt", "iyr", "hcl", "byr", "pid", "cid", "eyr", "ecl"],
["hcl", "ecl", "eyr", "hgt", "pid", "byr", "iyr", "cid"],
["iyr", "pid", "hcl", "ecl", "byr", "cid", "hgt", "eyr"],
["byr", "eyr", "iyr", "cid", "ecl", "hgt", "hcl", "pid"],
["hcl", "hgt", "eyr", "byr", "cid", "pid", "iyr", "ecl"],
["hgt", "pid", "ecl", "eyr", "hcl", "cid", "byr", "iyr"],
["hcl", "byr", "eyr", "pid", "cid", "hgt", "iyr"],
["iyr", "byr", "hcl", "cid", "pid", "hgt", "ecl", "eyr"],
["iyr", "hgt", "ecl", "byr", "hcl"],
["pid", "iyr", "byr", "ecl", "hcl", "hgt", "eyr"],
["eyr", "pid", "iyr", "hgt", "hcl", "ecl", "byr"],
["byr", "hgt", "ecl", "pid", "hcl", "cid", "eyr", "iyr"],
["pid", "iyr", "hcl", "byr", "eyr", "hgt", "ecl"],
["pid", "eyr", "hcl", "byr", "iyr", "ecl", "hgt"],
["iyr", "hgt", "ecl", "pid", "hcl", "eyr", "cid", "byr"],
["iyr", "cid", "hcl", "pid", "ecl", "hgt", "byr", "eyr"],
["ecl", "eyr", "hgt", "hcl", "pid", "byr", "iyr"],
["hcl", "ecl", "byr", "hgt", "pid", "cid", "eyr"],
["byr", "ecl", "eyr", "hgt", "iyr", "pid", "hcl"],
["hgt", "hcl", "eyr", "ecl", "pid", "byr"],
["eyr", "cid", "byr", "pid", "hcl", "ecl", "iyr", "hgt"],
["iyr", "ecl", "pid", "eyr", "hgt", "byr", "hcl"],
["hcl", "byr", "iyr", "ecl", "hgt", "cid", "eyr", "pid"],
["iyr", "hgt", "byr", "pid", "eyr", "hcl", "ecl"],
["eyr", "ecl", "pid", "iyr", "hgt", "hcl", "cid", "byr"],
["byr", "ecl", "pid", "iyr", "hcl", "eyr", "cid", "hgt"],
["cid", "byr", "hgt", "eyr", "iyr", "ecl", "pid", "hcl"],
["pid", "hgt", "ecl", "iyr", "eyr", "hcl"],
["eyr", "byr", "hcl", "ecl", "cid", "pid", "hgt", "iyr"],
["iyr", "hcl", "byr", "ecl", "pid"],
["byr", "cid", "hgt", "hcl", "pid", "eyr", "iyr", "ecl"],
["iyr", "eyr", "pid", "byr", "ecl", "cid", "hcl", "hgt"],
["hcl", "byr", "iyr", "pid", "eyr", "hgt", "ecl"],
["ecl", "iyr", "byr", "eyr", "hcl", "hgt", "pid"],
["ecl", "eyr", "iyr", "pid", "cid", "hgt", "byr", "hcl"],
["hcl", "pid", "eyr", "iyr", "byr", "ecl", "hgt"],
["eyr", "iyr", "hcl", "hgt", "pid", "byr", "ecl"],
["hcl", "byr", "iyr", "pid", "cid", "hgt", "ecl", "eyr"],
["iyr", "eyr", "hgt", "ecl", "byr", "hcl", "pid"],
["pid", "iyr", "hgt", "ecl", "byr", "hcl", "eyr"],
["eyr", "ecl", "iyr", "hcl", "byr", "pid", "hgt"],
["hgt", "iyr", "pid", "byr", "hcl", "eyr", "ecl"],
["byr", "eyr", "hgt", "hcl", "iyr", "pid", "ecl"],
["byr", "hcl", "pid", "eyr", "iyr", "hgt", "ecl"],
["hcl", "hgt", "byr", "eyr", "ecl", "iyr", "pid"],
["hcl", "pid", "byr", "hgt", "iyr", "eyr", "ecl"],
["hcl", "eyr", "byr", "cid", "pid", "hgt", "ecl", "iyr"],
["byr", "hgt", "iyr", "hcl", "pid", "ecl"],
["ecl", "byr", "pid", "hcl", "hgt", "eyr", "iyr"],
["byr", "iyr", "hgt", "pid", "hcl", "ecl", "eyr"],
["cid", "hcl", "byr", "iyr", "eyr", "pid", "ecl", "hgt"],
["hcl", "ecl", "hgt", "eyr", "pid", "iyr", "byr"],
["pid", "ecl", "iyr", "hcl", "byr", "eyr", "hgt"],
["pid", "cid", "iyr", "hcl", "byr", "hgt", "ecl"],
["hgt", "byr", "iyr", "eyr", "ecl", "pid", "hcl"],
["pid", "ecl", "hgt", "iyr", "byr", "hcl", "eyr"],
["ecl", "iyr", "byr", "eyr", "hgt", "cid", "hcl", "pid"],
["eyr", "iyr", "pid", "byr", "hcl", "cid", "ecl", "hgt"],
["hcl", "iyr", "cid", "eyr", "byr", "ecl", "hgt"],
["iyr", "ecl", "hgt", "hcl", "pid", "byr"],
["hgt", "ecl", "pid", "eyr", "iyr", "cid", "hcl", "byr"],
["hgt", "cid", "byr", "iyr", "eyr", "hcl", "pid", "ecl"],
["hgt", "iyr", "ecl", "eyr", "pid", "cid", "byr"],
["byr", "hcl", "ecl", "eyr", "hgt", "iyr", "pid"],
["byr", "cid", "iyr", "hgt", "hcl", "eyr", "pid", "ecl"],
["eyr", "pid", "hcl", "iyr", "byr", "hgt", "ecl"],
["byr", "ecl", "hcl", "pid", "eyr", "iyr", "cid", "hgt"],
["byr", "ecl", "iyr", "eyr", "hcl", "cid", "pid", "hgt"],
["eyr", "hgt", "iyr", "byr", "pid", "hcl", "ecl"],
["hcl", "eyr", "pid", "byr", "cid", "ecl", "hgt", "iyr"],
["ecl", "eyr", "byr", "iyr", "pid", "cid", "hgt"],
["pid", "hgt", "iyr", "eyr", "byr", "ecl", "hcl"],
["hgt", "iyr", "ecl", "pid", "hcl", "eyr", "byr"],
["pid", "hcl", "eyr", "hgt", "byr", "iyr", "ecl"],
["byr", "eyr", "cid", "hcl", "pid", "ecl", "hgt", "iyr"],
["eyr", "cid", "pid", "byr", "iyr", "hgt", "hcl", "ecl"],
["iyr", "hgt", "hcl", "byr", "ecl", "pid", "eyr"],
["pid", "eyr", "hcl", "iyr", "hgt", "ecl"],
["hcl", "ecl", "byr", "eyr", "iyr", "hgt", "pid"],
["iyr", "eyr", "pid", "ecl", "hcl", "cid", "byr", "hgt"],
["eyr", "cid", "hgt", "iyr", "ecl", "pid", "byr"],
["eyr", "byr", "ecl", "pid", "iyr", "hgt", "hcl"],
["cid", "hcl", "eyr", "iyr", "ecl", "byr", "pid", "hgt"],
["eyr", "pid", "byr", "hcl", "iyr", "ecl", "hgt"],
["cid", "byr", "iyr", "hgt", "hcl", "ecl", "eyr", "pid"],
["ecl", "iyr", "hgt", "byr", "pid"],
["eyr", "hgt", "pid", "iyr", "ecl", "byr", "hcl", "cid"],
["iyr", "hgt", "pid", "eyr", "ecl", "byr", "hcl"],
["eyr", "iyr", "hcl", "pid", "ecl", "byr", "hgt"],
["eyr", "hgt", "byr", "cid", "hcl", "iyr", "ecl"],
["eyr", "iyr", "hgt", "byr", "pid", "cid", "ecl", "hcl"],
["pid", "eyr", "ecl", "byr", "iyr", "hcl", "hgt"],
["hgt", "cid", "iyr", "byr", "hcl", "eyr", "pid", "ecl"],
["ecl", "hgt", "cid", "iyr", "byr", "eyr", "hcl", "pid"],
["hcl", "hgt", "eyr", "ecl", "iyr", "byr"],
["byr", "hgt", "eyr", "pid", "ecl", "iyr", "hcl"],
["byr", "eyr", "iyr", "hgt", "hcl", "ecl", "pid"],
["hgt", "iyr", "eyr", "hcl", "byr", "cid", "pid", "ecl"],
["iyr", "eyr", "pid", "byr", "hgt", "ecl", "hcl"],
["hcl", "iyr", "hgt", "pid", "byr", "ecl", "cid"],
["hgt", "hcl", "byr", "iyr", "pid", "eyr"],
["iyr", "byr", "pid", "eyr", "hgt", "cid", "hcl"],
["byr", "hgt", "iyr", "hcl", "pid", "ecl", "eyr"],
["pid", "byr", "cid", "hcl", "iyr", "hgt", "eyr", "ecl"],
["hcl", "hgt", "eyr", "byr", "pid", "cid", "ecl", "iyr"],
["cid", "pid", "eyr", "byr", "iyr", "ecl", "hgt", "hcl"],
["hcl", "byr", "iyr", "eyr", "hgt", "ecl", "pid"],
["hcl", "hgt", "ecl", "byr", "iyr", "cid", "eyr", "pid"],
["pid", "ecl", "iyr", "cid", "byr", "eyr", "hcl", "hgt"],
["pid", "iyr", "hcl", "eyr", "hgt", "ecl", "byr"],
["ecl", "iyr", "pid", "eyr", "hgt", "hcl", "byr"],
["iyr", "pid", "hcl", "hgt", "eyr", "cid", "ecl", "byr"],
["eyr", "pid", "byr", "hgt", "iyr", "ecl", "hcl"],
["cid", "eyr", "hgt", "byr", "ecl", "hcl", "iyr", "pid"],
["hcl", "iyr", "byr", "eyr", "hgt", "ecl", "pid"],
["eyr", "hcl", "byr", "ecl", "cid", "iyr", "pid"],
["hcl", "ecl", "iyr", "eyr", "pid", "byr", "cid", "hgt"],
["ecl", "hgt", "cid", "hcl", "pid", "iyr", "byr", "eyr"]];

var pesos = new Object();
pesos["byr"] = 1;
pesos["iyr"] = 1;
pesos["eyr"] = 1;
pesos["hgt"] = 1;
pesos["hcl"] = 1;
pesos["ecl"] = 1;
pesos["pid"] = 1;
pesos["cid"] = 2;

let validCounter = 0;
let invalidIndexes = []
for (let i = 0; i < propertiesArrays.length; i++) {
    const propArray = propertiesArrays[i];
    let pesoActual = 0;
    if (propArray.length >= 7) {
        for (let j = 0; j < propArray.length; j++) {
            const property = propArray[j];
            pesoActual += pesos[property];
        }
        if (pesoActual == 9 || pesoActual == 7) {
            validCounter += 1;
        } 
    }
    

}
console.log(validCounter);

let validCounter2 = 0;
let invalidIndexes2 = [];
for (let m = 0; m < propertiesArrays.length; m++) {
    const propArray = propertiesArrays[m];
    if (propArray.length == 8) {
        validCounter2 += 1;
    } else if (propArray.length == 7) {
        validCounter2 += 1;
        for (let n = 0; n < propArray.length; n++) {
            const property = propArray[n];
            if (property == "cid") {
                validCounter2 -= 1;
            }
        }
    } 
}

console.log(validCounter2);
