var bagsColorRules = {"bright olive": {"dotted white": 5, "wavy lavender": 2},
"plaid brown": {"bright lime": 3, "plaid coral": 5},
"dim coral": {"shiny maroon": 1, "bright orange": 2, "clear lavender": 3},
"dull olive": {"wavy purple": 5, "plaid white": 2, "vibrant magenta": 4, "light brown": 1},
"dim yellow": {"bright cyan": 1, "striped green": 3, "dim white": 5},
"drab chartreuse": {"shiny lime": 3, "bright indigo": 2, "muted yellow": 2, "dim tan": 5},
"dim cyan": {"drab tomato": 4, "dotted teal": 3, "posh purple": 1, "faded brown": 2},
"striped indigo": {"wavy brown": 2},
"dull coral": {"mirrored salmon": 5},
"light violet": {"light maroon": 3, "plaid purple": 3, "pale lime": 1, "pale orange": 2},
"clear magenta": {"muted tan": 3, "clear lime": 3, "bright magenta": 3, "faded purple": 3},
"drab turquoise": {"dark violet": 1},
"dim black": {"vibrant turquoise": 4},
"dotted gray": {"posh salmon": 1, "drab lime": 5, "clear coral": 1, "faded lime": 1},
"light lime": {"wavy lavender": 5, "shiny black": 3},
"bright yellow": {"dotted beige": 3, "clear purple": 4, "faded salmon": 4, "drab black": 5},
"shiny teal": {"dotted chartreuse": 3, "wavy yellow": 1, "clear lavender": 3},
"shiny crimson": {"light plum": 2, "shiny black": 3},
"shiny lime": {"dim turquoise": 1, "pale fuchsia": 4},
"pale lavender": {"bright lavender": 3, "wavy blue": 5},
"shiny purple": {},
"clear lime": {"drab bronze": 2},
"vibrant lavender": {"plaid crimson": 2, "plaid yellow": 3},
"clear gray": {"shiny indigo": 4, "vibrant salmon": 1, "bright yellow": 3, "light green": 2},
"dark lime": {"light lime": 1, "vibrant yellow": 3, "faded bronze": 5},
"bright chartreuse": {"mirrored olive": 5, "mirrored white": 2, "bright black": 1, "clear olive": 2},
"wavy red": {"bright black": 5, "dotted salmon": 4, "clear tomato": 4, "faded teal": 4},
"posh coral": {"posh plum": 4, "shiny magenta": 4, "light plum": 4},
"shiny coral": {"shiny yellow": 5},
"light bronze": {"shiny purple": 2, "mirrored maroon": 5, "light white": 2},
"mirrored olive": {"mirrored white": 5},
"pale crimson": {"vibrant gold": 2, "bright yellow": 1, "light green": 2, "shiny gray": 4},
"bright cyan": {"muted plum": 1, "dark bronze": 5, "dotted teal": 4, "faded fuchsia": 5},
"posh bronze": {"muted gold": 1, "shiny turquoise": 5, "wavy bronze": 3},
"mirrored yellow": {"dull maroon": 1, "posh orange": 2, "striped lime": 3, "plaid crimson": 4},
"muted brown": {"mirrored indigo": 5},
"posh lavender": {"dotted violet": 2, "clear orange": 3},
"shiny salmon": {"bright red": 3, "light turquoise": 1, "drab turquoise": 2},
"striped teal": {},
"pale purple": {"faded yellow": 1, "dotted beige": 2, "dark red": 1, "plaid yellow": 5},
"drab tomato": {"faded aqua": 2, "faded purple": 2},
"wavy yellow": {"wavy gold": 2, "dotted beige": 1, "shiny gold": 2, "posh tomato": 4},
"shiny yellow": {"wavy brown": 3, "dull violet": 5, "muted tomato": 2, "dull magenta": 4},
"wavy brown": {},
"faded teal": {"muted plum": 5, "posh indigo": 1},
"vibrant tomato": {"pale blue": 1},
"drab red": {"light teal": 3, "shiny lime": 4},
"muted beige": {"light teal": 4, "vibrant orange": 2, "drab turquoise": 1},
"dotted orange": {"plaid cyan": 3, "shiny beige": 3, "bright chartreuse": 1},
"posh fuchsia": {"posh tomato": 3, "bright blue": 5},
"striped lime": {"vibrant red": 4, "bright yellow": 1, "faded yellow": 5, "dim gold": 3},
"bright white": {"clear purple": 1, "drab crimson": 2},
"wavy olive": {"pale lavender": 1, "dotted lime": 2},
"clear black": {"pale yellow": 2},
"clear brown": {"vibrant crimson": 2},
"dotted aqua": {"light green": 4, "light purple": 4, "pale blue": 3},
"dull red": {"bright fuchsia": 1, "plaid crimson": 2, "dotted salmon": 5, "light salmon": 1},
"light red": {"mirrored purple": 2, "dull teal": 2},
"mirrored bronze": {"striped lavender": 4, "dotted brown": 1, "posh maroon": 1, "shiny chartreuse": 1},
"light silver": {"dim orange": 4, "dim aqua": 1, "plaid crimson": 5},
"faded violet": {"dotted tomato": 5, "wavy beige": 3},
"muted violet": {"dotted brown": 1},
"muted black": {"shiny purple": 3, "dark salmon": 1, "bright lavender": 3, "shiny white": 2},
"muted tomato": {"dull magenta": 3, "muted fuchsia": 1},
"faded olive": {"bright coral": 3, "dark salmon": 5, "dotted lavender": 3, "vibrant purple": 5},
"dotted indigo": {"drab yellow": 2, "dim coral": 5, "striped green": 3},
"dull turquoise": {"dark black": 3},
"faded fuchsia": {"dull green": 4, "pale lavender": 5},
"mirrored gray": {"mirrored brown": 2, "shiny gray": 3, "light maroon": 2},
"dull violet": {"muted tomato": 5},
"vibrant crimson": {"vibrant tomato": 1, "striped maroon": 1, "drab plum": 3},
"pale olive": {"shiny lime": 3, "dim turquoise": 4},
"muted orange": {"dull orange": 1, "shiny tomato": 5, "pale yellow": 5, "faded orange": 1},
"vibrant orange": {"muted yellow": 5, "plaid salmon": 1, "dim aqua": 5},
"bright brown": {"muted gray": 3, "dull cyan": 2},
"clear coral": {"clear crimson": 3, "dotted yellow": 4, "bright orange": 1},
"clear blue": {"posh tan": 1},
"shiny cyan": {"light gold": 3},
"plaid tomato": {"dull magenta": 3, "clear brown": 2, "wavy plum": 1},
"dim magenta": {"dark orange": 5},
"mirrored plum": {"dull green": 3, "light violet": 4, "vibrant bronze": 2, "vibrant tomato": 4},
"muted green": {"dull crimson": 1, "drab crimson": 2, "dim red": 2},
"wavy gray": {"dark silver": 3},
"mirrored white": {"bright yellow": 4, "bright blue": 2},
"dark white": {"posh turquoise": 2, "light plum": 2},
"striped maroon": {"shiny white": 5, "shiny coral": 3, "pale salmon": 3},
"shiny aqua": {"bright indigo": 1, "dim plum": 5},
"vibrant chartreuse": {"drab gold": 3, "striped cyan": 1, "drab violet": 2, "muted black": 1},
"faded chartreuse": {"bright bronze": 4, "dark silver": 3, "bright aqua": 1},
"shiny olive": {"light silver": 1},
"dim chartreuse": {"striped tomato": 5},
"vibrant red": {"mirrored beige": 3},
"vibrant white": {"light aqua": 4},
"dim gold": {"plaid gray": 3},
"posh chartreuse": {"wavy blue": 3, "dull maroon": 5, "muted yellow": 5},
"striped purple": {"shiny orange": 4, "dim lavender": 3, "muted lavender": 3, "plaid tomato": 5},
"plaid white": {"striped salmon": 2},
"striped tomato": {"bright blue": 5},
"bright lime": {"dark maroon": 5, "shiny gray": 1, "light white": 3},
"vibrant yellow": {"plaid magenta": 3, "wavy chartreuse": 3, "bright lavender": 3, "vibrant salmon": 1},
"faded red": {"plaid turquoise": 3, "wavy cyan": 2, "dim chartreuse": 5},
"dim red": {"muted coral": 4},
"dotted beige": {},
"pale magenta": {"light violet": 1, "mirrored lime": 2},
"muted fuchsia": {},
"vibrant purple": {"shiny purple": 5, "dim turquoise": 4, "bright violet": 2, "dotted beige": 1},
"pale tomato": {"dull magenta": 3, "dim turquoise": 5},
"wavy gold": {"muted tomato": 2, "posh tomato": 5},
"dull green": {"shiny indigo": 1, "dull maroon": 3},
"muted magenta": {"clear tan": 1, "dim tomato": 5, "plaid purple": 1, "wavy gray": 1},
"drab bronze": {"dull violet": 5, "light green": 1, "dim turquoise": 3},
"vibrant coral": {"bright black": 5, "vibrant salmon": 5},
"dim gray": {},
"mirrored black": {"mirrored lavender": 5},
"muted cyan": {"mirrored gold": 5},
"light aqua": {"dull cyan": 1, "dull lavender": 4, "wavy crimson": 2},
"mirrored gold": {"light orange": 1},
"vibrant cyan": {"pale chartreuse": 2, "vibrant tan": 5},
"dotted green": {"vibrant tan": 2},
"vibrant tan": {"pale lime": 5},
"drab magenta": {"light gold": 3, "posh yellow": 2, "mirrored salmon": 4, "muted black": 4},
"clear teal": {"vibrant red": 3, "dotted crimson": 3, "plaid fuchsia": 3},
"dark coral": {"posh fuchsia": 4, "mirrored fuchsia": 5},
"bright plum": {"vibrant blue": 5},
"drab indigo": {"shiny orange": 2, "light indigo": 3, "drab crimson": 2, "light purple": 5},
"shiny chartreuse": {"clear gold": 4},
"plaid coral": {"shiny white": 1, "dotted plum": 2, "wavy indigo": 5},
"dull silver": {"striped white": 3, "faded gold": 2, "dark fuchsia": 3},
"dotted teal": {"clear lime": 5},
"posh black": {"light plum": 4, "dark plum": 4, "vibrant plum": 4},
"wavy black": {"bright bronze": 5},
"mirrored magenta": {"muted olive": 3, "striped tomato": 5, "clear lavender": 2},
"posh indigo": {"clear salmon": 4, "vibrant salmon": 3},
"vibrant brown": {"drab turquoise": 2},
"pale blue": {"vibrant silver": 3, "plaid turquoise": 5},
"wavy lavender": {"plaid lime": 5, "plaid crimson": 1, "wavy coral": 5, "dark gold": 1},
"shiny tan": {"plaid blue": 5, "shiny bronze": 3, "mirrored gold": 1, "faded salmon": 4},
"muted purple": {"muted tan": 3},
"mirrored crimson": {"drab plum": 2, "muted magenta": 3, "dim yellow": 5},
"muted red": {"wavy indigo": 1},
"dotted tomato": {"plaid turquoise": 5, "dull lime": 1},
"dull orange": {"shiny yellow": 2, "drab bronze": 1, "shiny lime": 4},
"clear aqua": {"dull cyan": 3, "bright yellow": 2, "shiny maroon": 2},
"light coral": {"wavy black": 4},
"posh silver": {"light bronze": 5, "clear purple": 2, "pale fuchsia": 5, "dull cyan": 2},
"drab coral": {"posh yellow": 2},
"light fuchsia": {"dim gray": 2},
"faded cyan": {"faded orange": 1},
"bright aqua": {"muted black": 1, "muted chartreuse": 1, "wavy blue": 1},
"drab lavender": {"posh yellow": 4},
"posh gray": {"shiny lime": 4, "dotted gold": 5, "vibrant maroon": 4},
"plaid blue": {"vibrant tan": 5, "mirrored white": 5, "shiny purple": 5, "clear white": 1},
"shiny gray": {"muted fuchsia": 2, "plaid crimson": 5, "faded salmon": 5},
"light brown": {"dotted tan": 4, "wavy coral": 5, "plaid teal": 3},
"striped magenta": {"wavy turquoise": 2},
"striped aqua": {"light cyan": 2, "plaid lime": 2, "mirrored orange": 2, "posh lime": 1},
"bright teal": {"faded plum": 1, "dark blue": 1, "posh cyan": 1, "striped chartreuse": 2},
"pale green": {"muted black": 1, "faded olive": 4, "wavy chartreuse": 1, "dim maroon": 5},
"vibrant bronze": {"vibrant lavender": 3, "faded blue": 3, "dim brown": 4, "drab chartreuse": 4},
"pale brown": {"faded yellow": 3, "vibrant tomato": 1},
"wavy aqua": {"striped magenta": 1, "mirrored silver": 1, "dim gold": 1},
"dotted yellow": {"drab turquoise": 2, "drab maroon": 2, "light teal": 1},
"pale salmon": {"bright indigo": 2, "wavy violet": 3},
"posh red": {"posh blue": 3, "muted yellow": 4, "dark silver": 5},
"wavy violet": {"dotted lime": 2, "vibrant purple": 2, "dull maroon": 1},
"drab purple": {"plaid crimson": 4, "shiny plum": 1},
"light black": {"faded teal": 2, "faded yellow": 1, "muted fuchsia": 2},
"dim turquoise": {"wavy beige": 4, "shiny plum": 1, "muted tomato": 3, "dull magenta": 4},
"dark tan": {"drab chartreuse": 5, "dim coral": 3},
"striped gray": {"muted red": 5, "bright blue": 1, "wavy maroon": 5},
"muted tan": {"drab turquoise": 5, "light maroon": 1, "plaid purple": 5},
"posh green": {"dotted chartreuse": 3, "muted yellow": 4, "shiny gray": 5, "dark black": 1},
"mirrored lime": {"clear teal": 4, "wavy coral": 5, "mirrored beige": 2},
"muted plum": {"faded yellow": 5, "posh blue": 3},
"dark maroon": {"dotted lavender": 2},
"plaid green": {"wavy yellow": 3, "shiny indigo": 1, "mirrored maroon": 4, "dim gray": 5},
"mirrored teal": {"dim magenta": 5, "dark magenta": 1, "plaid green": 3},
"wavy crimson": {"vibrant cyan": 1, "light beige": 2},
"wavy green": {"dim tan": 4, "dotted lime": 1, "drab white": 5, "bright beige": 2},
"shiny brown": {"dark silver": 5, "shiny maroon": 3, "dotted lavender": 5},
"muted turquoise": {"dark indigo": 5, "drab plum": 3},
"mirrored lavender": {"clear salmon": 2, "plaid maroon": 2, "wavy cyan": 3},
"drab blue": {"dotted olive": 3, "shiny chartreuse": 1, "drab magenta": 1, "mirrored maroon": 2},
"bright fuchsia": {"dark olive": 1},
"pale turquoise": {"striped chartreuse": 2},
"posh white": {"striped cyan": 1, "plaid coral": 1, "dim gray": 2, "shiny red": 3},
"drab brown": {"plaid red": 4},
"pale gold": {"dim tan": 2, "dark red": 5, "vibrant cyan": 4, "dark violet": 5},
"plaid maroon": {"shiny lime": 1, "faded lavender": 4, "dim tan": 2, "vibrant purple": 5},
"vibrant green": {"drab purple": 1, "faded blue": 2},
"bright violet": {"dotted lavender": 1, "light chartreuse": 5, "bright indigo": 4},
"bright magenta": {"shiny purple": 5, "light teal": 5, "pale purple": 2, "pale silver": 4},
"plaid orange": {"dull green": 1},
"posh olive": {"dark silver": 5, "drab yellow": 3, "dim brown": 2, "dull gray": 4},
"light teal": {"dim gray": 3},
"shiny beige": {"dark cyan": 1, "vibrant yellow": 1},
"drab cyan": {"dim silver": 4, "wavy maroon": 1},
"pale gray": {"dark salmon": 2},
"plaid beige": {"bright purple": 3, "drab plum": 1, "shiny bronze": 4, "drab salmon": 3},
"dull plum": {"mirrored orange": 4},
"shiny violet": {"drab olive": 3},
"striped turquoise": {"faded green": 1},
"dark aqua": {"clear crimson": 5},
"dim crimson": {"faded chartreuse": 3, "light orange": 3, "striped plum": 4},
"faded tan": {"dark cyan": 1, "bright silver": 1},
"faded brown": {"faded purple": 3, "posh orange": 1, "light silver": 5},
"mirrored coral": {"vibrant tan": 1},
"clear olive": {"pale olive": 2},
"pale lime": {"muted fuchsia": 2, "dim gray": 1, "dotted beige": 5, "striped teal": 5},
"wavy white": {"dim indigo": 3, "plaid green": 3, "dull gold": 2},
"pale plum": {"plaid gray": 5},
"plaid yellow": {"dark yellow": 5, "mirrored white": 1, "shiny white": 5, "shiny lime": 1},
"drab salmon": {"vibrant blue": 2, "plaid plum": 2, "shiny gray": 1, "bright black": 3},
"striped fuchsia": {"striped teal": 2, "drab black": 5, "bright magenta": 2},
"mirrored fuchsia": {"drab black": 3},
"dark indigo": {"dull lime": 1, "vibrant cyan": 4, "bright gray": 1, "pale purple": 3},
"posh blue": {"shiny yellow": 1},
"dark turquoise": {"bright yellow": 4, "wavy bronze": 3},
"posh tan": {"shiny plum": 4, "dark silver": 4, "wavy beige": 3, "mirrored fuchsia": 1},
"bright turquoise": {"dotted green": 1, "faded silver": 4, "plaid turquoise": 1},
"vibrant teal": {"plaid teal": 4, "pale blue": 3},
"plaid purple": {"dim tan": 2, "light turquoise": 5},
"drab plum": {"dull green": 2, "posh lavender": 5, "drab tan": 3},
"dark blue": {"mirrored indigo": 3, "dark red": 3},
"vibrant black": {"shiny red": 2, "posh brown": 5, "mirrored yellow": 1},
"mirrored brown": {"shiny indigo": 1, "shiny yellow": 2, "shiny blue": 5, "clear yellow": 5},
"dotted crimson": {"posh tomato": 3, "vibrant blue": 4, "dark violet": 5, "posh violet": 5},
"shiny bronze": {"plaid maroon": 1},
"drab orange": {"dotted crimson": 4, "clear bronze": 4, "pale turquoise": 3, "dim coral": 5},
"wavy fuchsia": {"posh fuchsia": 4, "wavy purple": 5, "muted cyan": 2},
"plaid black": {"drab crimson": 2, "vibrant tomato": 4, "clear bronze": 4, "faded lavender": 4},
"mirrored red": {"shiny crimson": 3},
"faded tomato": {"clear aqua": 1, "vibrant bronze": 3},
"light turquoise": {"posh silver": 2, "shiny black": 2, "muted blue": 5},
"faded crimson": {"posh blue": 5, "dim maroon": 4},
"dull magenta": {},
"dark plum": {"vibrant purple": 5, "wavy brown": 5, "dark indigo": 2},
"dotted white": {"dark teal": 1, "dull white": 5, "pale salmon": 2, "dotted plum": 1},
"wavy indigo": {"shiny maroon": 5, "shiny lime": 4},
"faded coral": {"dim indigo": 5, "striped brown": 1},
"vibrant turquoise": {"dotted magenta": 4, "bright lavender": 5, "plaid turquoise": 5, "striped lavender": 5},
"muted gray": {"mirrored white": 1},
"dotted gold": {"dark brown": 4},
"dim salmon": {"light gold": 3, "plaid purple": 4},
"clear salmon": {"striped lavender": 3, "posh teal": 5, "vibrant turquoise": 4},
"vibrant olive": {"striped fuchsia": 3, "muted indigo": 3, "dotted yellow": 1, "bright white": 4},
"bright salmon": {"drab orange": 1},
"muted maroon": {"dim crimson": 5, "dark red": 4, "plaid purple": 5},
"light tan": {"dotted blue": 2},
"dotted turquoise": {"faded lime": 4, "dotted silver": 2, "mirrored cyan": 4},
"shiny magenta": {"mirrored salmon": 1, "dim fuchsia": 3, "muted red": 3},
"dark cyan": {"dark brown": 5, "vibrant silver": 5, "dim green": 5},
"dim violet": {"vibrant turquoise": 4, "pale crimson": 1, "bright red": 4, "muted black": 3},
"dull aqua": {"drab teal": 3},
"dim aqua": {"vibrant blue": 3, "pale salmon": 4, "shiny bronze": 5, "dim olive": 2},
"light gray": {"dull white": 4, "dim blue": 4},
"dull salmon": {"striped fuchsia": 1, "dark white": 5, "pale tan": 2},
"plaid teal": {"dim olive": 1, "faded purple": 2, "shiny gray": 4, "shiny salmon": 1},
"clear tan": {"clear lime": 1, "mirrored turquoise": 4, "bright white": 4, "drab bronze": 3},
"wavy beige": {"muted fuchsia": 2, "clear bronze": 3, "bright yellow": 2},
"plaid salmon": {"drab bronze": 2, "drab chartreuse": 2, "plaid crimson": 4, "shiny lime": 5},
"drab lime": {"clear orange": 2, "dotted silver": 4, "dark maroon": 5, "dim magenta": 5},
"bright crimson": {"shiny maroon": 5},
"clear turquoise": {"vibrant blue": 4},
"clear lavender": {"pale fuchsia": 3, "bright lavender": 2, "dark orange": 2, "dull magenta": 1},
"clear green": {"clear orange": 3},
"pale cyan": {"dull purple": 2, "clear olive": 1},
"posh lime": {"clear purple": 2},
"dim lavender": {"clear crimson": 3, "striped violet": 4},
"faded indigo": {"dull cyan": 5, "plaid blue": 2, "striped teal": 4},
"posh aqua": {"bright aqua": 5, "shiny indigo": 2, "drab silver": 2, "vibrant turquoise": 1},
"dark magenta": {"light silver": 3},
"clear cyan": {"pale fuchsia": 3, "shiny coral": 2, "dull magenta": 1, "dim turquoise": 4},
"pale yellow": {"vibrant tan": 1, "drab plum": 4},
"dim plum": {"striped gray": 4, "posh tomato": 2, "drab black": 1},
"dark purple": {"bright indigo": 3, "dull purple": 3},
"clear plum": {"bright cyan": 4, "dim turquoise": 5},
"faded magenta": {"muted olive": 1, "plaid chartreuse": 3},
"mirrored aqua": {"clear lavender": 2},
"light white": {"dim gray": 3, "bright white": 3, "striped teal": 2, "light green": 4},
"clear gold": {"wavy coral": 2},
"dull lavender": {"wavy beige": 2, "drab black": 3},
"dark yellow": {"wavy gray": 3, "dark salmon": 1, "vibrant tan": 2},
"dotted black": {"dim plum": 4, "bright white": 2},
"posh tomato": {"wavy beige": 5, "dim gray": 1, "shiny lime": 3, "bright black": 5},
"bright indigo": {"striped teal": 4, "shiny yellow": 1, "dotted beige": 5},
"dim purple": {"dark tan": 5, "striped lavender": 5},
"posh plum": {"posh maroon": 5},
"pale bronze": {"shiny silver": 5},
"striped crimson": {"dark indigo": 2},
"plaid fuchsia": {"shiny lime": 1, "mirrored orange": 4},
"dark orange": {"dotted lavender": 2, "posh blue": 1, "muted yellow": 2},
"dim blue": {"clear yellow": 2},
"clear violet": {"shiny bronze": 2},
"shiny blue": {"dark salmon": 4, "posh plum": 5},
"dull lime": {"plaid green": 5, "bright black": 3, "drab maroon": 4},
"muted lavender": {"dark gray": 1, "bright crimson": 2},
"plaid gray": {"bright black": 5, "pale silver": 5},
"light yellow": {"mirrored crimson": 2},
"muted chartreuse": {"pale fuchsia": 1, "plaid purple": 1},
"dim lime": {"dull maroon": 3, "bright red": 3, "drab black": 3},
"light purple": {"dull violet": 5, "vibrant lavender": 5},
"posh orange": {"pale salmon": 5, "light chartreuse": 5, "dark red": 1},
"vibrant violet": {"shiny gray": 3},
"pale silver": {"mirrored salmon": 5},
"light tomato": {"dim tan": 2, "faded silver": 1, "plaid yellow": 4, "drab gold": 3},
"posh salmon": {"bright plum": 3},
"dotted plum": {"pale gold": 4, "vibrant lavender": 1, "pale blue": 2},
"shiny lavender": {"dull gray": 1, "muted teal": 4, "dotted yellow": 2, "bright turquoise": 2},
"dim beige": {"wavy yellow": 2, "drab violet": 2, "wavy gold": 1, "clear cyan": 5},
"posh cyan": {"clear lavender": 2, "clear salmon": 4, "posh tan": 4},
"light maroon": {"dark violet": 5, "plaid lime": 3, "wavy gold": 3, "dotted lime": 5},
"dotted lime": {"clear bronze": 3, "dim turquoise": 5},
"dim bronze": {"light fuchsia": 3},
"faded black": {"light bronze": 3, "bright beige": 2},
"striped white": {"mirrored white": 1},
"clear red": {"pale orange": 1, "clear orange": 2, "dull maroon": 1, "dark bronze": 3},
"muted lime": {"dim fuchsia": 5},
"vibrant gold": {"wavy blue": 4, "clear gray": 3, "vibrant turquoise": 5},
"clear silver": {"light violet": 3, "dull turquoise": 5},
"muted indigo": {"dark orange": 3, "light gold": 4},
"bright green": {"dark red": 4},
"vibrant plum": {"dull tomato": 5, "bright cyan": 4, "plaid purple": 4},
"wavy cyan": {"muted plum": 4},
"plaid cyan": {"clear orange": 4, "dull chartreuse": 3},
"faded salmon": {"dim gray": 1},
"shiny turquoise": {"light aqua": 3, "vibrant beige": 1, "clear turquoise": 4, "faded silver": 1},
"dotted silver": {"dotted blue": 5, "dotted salmon": 1},
"striped black": {"plaid crimson": 2, "dotted silver": 5, "dull maroon": 5},
"dull indigo": {"dim magenta": 4, "shiny magenta": 4, "pale yellow": 2, "plaid cyan": 1},
"bright coral": {"shiny coral": 1, "muted tomato": 2, "drab crimson": 4},
"faded bronze": {"posh cyan": 5, "light beige": 5, "drab yellow": 1, "striped lime": 3},
"drab green": {"clear cyan": 1},
"pale black": {"muted yellow": 2},
"muted salmon": {"plaid crimson": 4, "vibrant lime": 2},
"dark violet": {"clear cyan": 4, "mirrored maroon": 1, "drab black": 5},
"faded aqua": {"pale fuchsia": 3, "clear teal": 1, "light white": 5},
"vibrant indigo": {"light turquoise": 5},
"bright blue": {"shiny purple": 1, "wavy brown": 1},
"dark olive": {"wavy beige": 2},
"vibrant beige": {"wavy beige": 3, "posh violet": 1, "dark teal": 4},
"dotted olive": {"dotted magenta": 5},
"muted coral": {"vibrant silver": 2, "dim coral": 3},
"dark chartreuse": {"faded tomato": 4, "light violet": 2, "clear silver": 4},
"light green": {},
"bright gray": {"drab yellow": 2, "muted indigo": 2},
"posh crimson": {"plaid indigo": 5, "wavy lime": 3, "dull turquoise": 2, "faded salmon": 5},
"drab yellow": {"shiny purple": 3, "dark salmon": 4, "shiny coral": 3, "shiny plum": 2},
"dull white": {"plaid lavender": 3, "dark beige": 4, "posh beige": 1},
"drab olive": {"shiny cyan": 1, "bright fuchsia": 3},
"striped olive": {"drab aqua": 2, "muted chartreuse": 3, "clear red": 2, "posh turquoise": 1},
"posh purple": {"dull lime": 1, "dull plum": 2, "dark black": 3},
"mirrored green": {"mirrored salmon": 2},
"dull teal": {"dark gray": 1, "posh indigo": 1, "light coral": 5},
"dim indigo": {"dark maroon": 5},
"faded gray": {"muted crimson": 4},
"light blue": {"plaid violet": 2, "dim tomato": 3, "plaid crimson": 4, "dull orange": 5},
"plaid turquoise": {"muted blue": 2, "clear white": 5, "dull violet": 1},
"striped gold": {"striped brown": 2, "wavy silver": 1},
"faded blue": {"dark lavender": 1, "muted yellow": 4, "bright yellow": 2, "dim tan": 2},
"clear beige": {"dim tan": 5, "faded blue": 4, "bright green": 2},
"shiny indigo": {"shiny purple": 1},
"striped brown": {"light gold": 2},
"shiny black": {"posh red": 1, "bright black": 5, "posh plum": 3, "clear white": 5},
"pale aqua": {"plaid purple": 5, "wavy orange": 3, "dotted purple": 5, "bright lime": 4},
"dark beige": {"clear white": 3, "wavy yellow": 3, "posh turquoise": 3, "posh tan": 2},
"striped green": {"posh red": 3, "shiny salmon": 2, "mirrored salmon": 4, "posh teal": 3},
"pale violet": {"wavy turquoise": 5, "bright aqua": 1},
"dim tomato": {"dim tan": 5},
"mirrored cyan": {"shiny indigo": 5, "faded blue": 3},
"plaid magenta": {"mirrored brown": 3, "pale olive": 5, "clear purple": 2},
"dotted tan": {"plaid turquoise": 5},
"dull fuchsia": {"shiny crimson": 2, "clear olive": 3},
"clear orange": {"dotted lime": 5, "dark olive": 2, "bright yellow": 3, "wavy violet": 2},
"light indigo": {"drab plum": 1, "dim lime": 5},
"muted aqua": {"faded red": 5, "pale blue": 5, "dull lavender": 5},
"faded plum": {"drab turquoise": 5},
"dark gold": {"faded salmon": 4, "bright black": 4, "dim chartreuse": 4},
"striped bronze": {"dark beige": 2},
"mirrored purple": {"dim turquoise": 3, "shiny bronze": 4},
"faded white": {"faded tomato": 4, "faded aqua": 3, "faded gold": 5, "vibrant orange": 4},
"wavy turquoise": {"dotted olive": 2, "muted yellow": 1},
"striped blue": {"wavy bronze": 5, "shiny chartreuse": 3},
"dull gray": {"pale lavender": 4},
"plaid plum": {"dim olive": 4, "faded olive": 3},
"pale coral": {"faded yellow": 1, "shiny plum": 3, "striped tomato": 4, "shiny bronze": 4},
"drab violet": {"plaid black": 2, "bright violet": 5, "pale blue": 3},
"vibrant gray": {"vibrant indigo": 4, "dull beige": 1, "dull plum": 1, "dotted brown": 1},
"drab gray": {"mirrored brown": 5, "bright coral": 5},
"pale chartreuse": {"dull cyan": 2, "mirrored fuchsia": 4},
"dotted lavender": {"bright blue": 2, "light chartreuse": 3},
"dull tomato": {"wavy yellow": 5},
"dull purple": {"wavy brown": 5, "muted yellow": 1},
"wavy orange": {"bright orange": 4, "dotted purple": 1, "dull blue": 3, "light crimson": 3},
"dotted purple": {"bright cyan": 1, "wavy violet": 5, "vibrant cyan": 3},
"light lavender": {"shiny salmon": 4, "mirrored salmon": 4, "wavy magenta": 2},
"plaid crimson": {"dotted salmon": 3, "plaid maroon": 2, "pale chartreuse": 5, "dotted beige": 3},
"plaid lavender": {"clear bronze": 2, "light silver": 5, "bright lavender": 1},
"wavy lime": {"dim coral": 1},
"clear tomato": {"dark violet": 1},
"light gold": {"striped teal": 1, "vibrant purple": 2, "dark salmon": 5},
"faded turquoise": {"shiny lime": 1, "posh orange": 1, "plaid maroon": 1},
"wavy tomato": {"plaid plum": 2, "dull lime": 1, "dull maroon": 3},
"faded beige": {"clear maroon": 3, "dotted brown": 1},
"dark black": {"faded salmon": 1, "light green": 1, "clear bronze": 4, "dotted lavender": 4},
"striped violet": {"mirrored beige": 4},
"plaid chartreuse": {"dotted purple": 2},
"posh maroon": {"wavy yellow": 5, "pale chartreuse": 2},
"posh yellow": {"mirrored blue": 5, "wavy beige": 2},
"bright black": {"clear bronze": 3, "wavy gray": 5},
"shiny tomato": {"dotted plum": 3, "shiny orange": 1, "faded teal": 4, "bright lavender": 1},
"dotted chartreuse": {"muted yellow": 2, "faded cyan": 4, "striped indigo": 3, "drab red": 1},
"pale tan": {"dotted chartreuse": 3},
"dim white": {"dim tomato": 2, "striped indigo": 3, "faded red": 1, "mirrored turquoise": 3},
"mirrored salmon": {"pale chartreuse": 1, "faded salmon": 3, "dark silver": 2},
"vibrant fuchsia": {"dim olive": 3, "striped magenta": 1, "dark magenta": 2, "drab white": 2},
"drab silver": {"dotted silver": 2, "wavy yellow": 4, "dim turquoise": 2, "shiny maroon": 2},
"dull yellow": {"posh teal": 2, "muted chartreuse": 1, "pale salmon": 1, "posh beige": 1},
"clear fuchsia": {"light turquoise": 4, "dull white": 1, "plaid indigo": 3, "shiny gold": 1},
"dark bronze": {"faded salmon": 2},
"vibrant lime": {"dull chartreuse": 3, "shiny yellow": 5},
"wavy tan": {"wavy indigo": 4, "dull crimson": 3},
"mirrored tan": {"dim salmon": 4, "dim tomato": 5, "mirrored salmon": 4, "drab indigo": 3},
"plaid bronze": {"dotted silver": 2, "striped black": 1, "dotted tomato": 2},
"shiny silver": {"muted salmon": 2, "bright magenta": 5, "drab lime": 2},
"mirrored violet": {"shiny yellow": 1, "vibrant tan": 5},
"dotted red": {"posh beige": 3, "posh lavender": 3, "shiny lavender": 3, "pale bronze": 4},
"mirrored chartreuse": {"dark coral": 3, "muted cyan": 1},
"drab crimson": {"bright blue": 4, "faded salmon": 4},
"striped salmon": {"posh fuchsia": 4, "faded salmon": 4, "shiny yellow": 3},
"dark gray": {"bright bronze": 3},
"striped tan": {"vibrant green": 3},
"dull maroon": {"muted tomato": 1},
"light crimson": {"posh green": 1},
"faded lavender": {"dotted beige": 2},
"clear white": {"bright bronze": 2, "wavy gray": 2, "dull magenta": 4, "shiny lime": 2},
"dim orange": {"drab gray": 5, "drab tan": 4, "faded black": 3, "pale cyan": 2},
"faded green": {"dim blue": 4},
"plaid aqua": {"drab indigo": 2, "pale turquoise": 5, "pale tomato": 1},
"dotted magenta": {"pale lavender": 5, "shiny yellow": 2, "posh tomato": 3},
"faded maroon": {"wavy plum": 5, "shiny lime": 2},
"dim silver": {"dull cyan": 2, "shiny salmon": 1, "striped salmon": 1},
"dotted salmon": {"posh tomato": 1, "bright black": 4},
"vibrant salmon": {"dark silver": 2},
"striped beige": {"clear tomato": 2, "mirrored indigo": 1, "pale chartreuse": 2, "dull yellow": 3},
"bright orange": {"pale lime": 1},
"muted crimson": {"dotted lavender": 1},
"muted bronze": {"light green": 3},
"shiny fuchsia": {"plaid indigo": 4, "bright fuchsia": 5},
"bright red": {"posh fuchsia": 2, "clear cyan": 2},
"dim maroon": {"dotted beige": 1, "drab black": 2, "posh tomato": 5, "striped lavender": 3},
"bright gold": {"dim chartreuse": 5, "vibrant salmon": 1, "faded black": 2},
"drab white": {"clear yellow": 1, "pale cyan": 4, "dark yellow": 5},
"clear purple": {"wavy brown": 2, "dull magenta": 3, "dim gray": 5, "shiny purple": 4},
"dim green": {"posh turquoise": 2, "light bronze": 4},
"dull blue": {"light salmon": 1, "posh red": 1, "clear brown": 2},
"bright silver": {"dotted bronze": 3, "plaid blue": 1, "light coral": 2},
"bright bronze": {"dull magenta": 3, "light white": 3},
"shiny gold": {"wavy gold": 3},
"wavy bronze": {"dull lime": 4, "shiny white": 2, "dim silver": 2},
"muted yellow": {"dark bronze": 5, "light white": 3, "shiny coral": 5, "shiny lime": 4},
"faded orange": {"plaid maroon": 3, "shiny plum": 5, "mirrored white": 2},
"vibrant silver": {"bright coral": 1, "wavy blue": 5, "mirrored maroon": 1},
"mirrored maroon": {"drab crimson": 5, "striped tomato": 4},
"striped silver": {"dotted olive": 2, "muted white": 3, "dark black": 5, "light gray": 5},
"drab gold": {"clear coral": 2},
"plaid tan": {"plaid orange": 2, "muted beige": 2, "mirrored purple": 2},
"bright beige": {"light plum": 5},
"light salmon": {"dark black": 1, "mirrored salmon": 5, "dim silver": 1},
"dull beige": {"dark lavender": 2},
"posh magenta": {"muted yellow": 3},
"dotted violet": {"wavy brown": 1, "dim turquoise": 3},
"vibrant blue": {"wavy gray": 4, "light turquoise": 2, "drab bronze": 1, "wavy cyan": 4},
"wavy purple": {"dotted olive": 3, "dull lime": 2},
"wavy plum": {"posh chartreuse": 3},
"dark silver": {},
"dark teal": {"posh red": 4, "dark lavender": 4},
"plaid lime": {"muted fuchsia": 2},
"posh violet": {"clear olive": 5},
"plaid olive": {"vibrant tan": 4, "plaid fuchsia": 5},
"mirrored indigo": {"posh maroon": 5, "light turquoise": 5},
"vibrant maroon": {"vibrant beige": 4},
"light magenta": {"vibrant gray": 2, "clear crimson": 4},
"clear indigo": {"light gray": 4, "plaid blue": 1},
"shiny red": {"vibrant blue": 4, "wavy brown": 1, "striped maroon": 5, "posh orange": 5},
"dark crimson": {"bright yellow": 2},
"dull crimson": {"striped salmon": 5, "faded purple": 3, "clear tomato": 4},
"pale red": {"dotted cyan": 1, "dark turquoise": 2},
"striped plum": {"faded yellow": 4, "posh blue": 1},
"dim olive": {"light green": 1, "faded salmon": 1},
"dim brown": {"drab bronze": 5, "dark red": 2, "shiny gold": 3},
"pale orange": {"pale gray": 3, "clear olive": 1},
"shiny green": {"clear turquoise": 2, "mirrored aqua": 1, "dull red": 2, "dull bronze": 4},
"dotted fuchsia": {"vibrant bronze": 3, "dull maroon": 1, "wavy indigo": 5},
"posh teal": {"pale blue": 4, "pale lime": 1},
"pale teal": {"muted beige": 5, "dark salmon": 5, "faded black": 2},
"vibrant aqua": {"vibrant silver": 5, "shiny maroon": 5},
"light olive": {"plaid turquoise": 2},
"dim teal": {"muted magenta": 1, "wavy maroon": 5, "striped brown": 5, "clear plum": 4},
"faded silver": {"dull lavender": 2},
"dark fuchsia": {"dim black": 2, "dotted olive": 3},
"dotted cyan": {"clear gold": 3},
"pale beige": {"clear turquoise": 2},
"vibrant magenta": {"light bronze": 5, "drab black": 3},
"pale indigo": {"vibrant cyan": 2},
"clear bronze": {"vibrant salmon": 1},
"pale white": {"faded orange": 4},
"light chartreuse": {},
"striped chartreuse": {"clear gray": 4},
"dark salmon": {"wavy gray": 5, "light chartreuse": 1, "clear gray": 2},
"muted gold": {"bright lavender": 3, "vibrant yellow": 4, "posh silver": 3},
"muted white": {"muted blue": 4, "light gold": 1},
"dim tan": {"posh fuchsia": 5, "wavy brown": 5, "dim turquoise": 1},
"dull black": {"dotted cyan": 5, "posh turquoise": 2, "pale salmon": 5},
"faded lime": {"mirrored orange": 4, "vibrant orange": 2, "dull lavender": 2, "dotted chartreuse": 3},
"drab tan": {"shiny maroon": 5, "mirrored white": 4, "dull plum": 3, "shiny plum": 4},
"muted olive": {"faded blue": 4},
"dull chartreuse": {"shiny cyan": 4, "dark silver": 5, "dark violet": 2, "bright lavender": 2},
"posh turquoise": {"pale orange": 4, "dotted yellow": 2, "bright tomato": 3, "vibrant turquoise": 2},
"dull tan": {"mirrored purple": 2},
"drab teal": {"dull lavender": 1},
"light beige": {"plaid yellow": 3, "faded lavender": 4},
"wavy blue": {"shiny purple": 3},
"striped orange": {"vibrant cyan": 4},
"shiny orange": {"shiny black": 2, "shiny coral": 2},
"dull brown": {"wavy bronze": 3},
"mirrored silver": {"vibrant tan": 4, "faded fuchsia": 4, "dark red": 5, "wavy blue": 3},
"wavy teal": {"pale coral": 1},
"drab black": {"wavy brown": 4, "striped teal": 4, "muted fuchsia": 2, "shiny indigo": 4},
"drab aqua": {"bright orange": 2, "vibrant tan": 1},
"mirrored orange": {"striped salmon": 2, "wavy gray": 1, "pale blue": 5, "mirrored salmon": 4},
"muted teal": {"drab tan": 4, "posh beige": 4, "faded green": 4},
"faded yellow": {"shiny purple": 3, "wavy blue": 3, "muted fuchsia": 1},
"shiny maroon": {"striped salmon": 3, "wavy violet": 5},
"wavy silver": {"faded blue": 4, "vibrant salmon": 2, "plaid gray": 5},
"shiny white": {"dark salmon": 4},
"posh brown": {"drab red": 5},
"bright purple": {"dim silver": 2},
"dotted brown": {"dotted yellow": 1},
"striped lavender": {"shiny gold": 5, "mirrored fuchsia": 5},
"dark lavender": {"bright violet": 3, "dull violet": 5, "shiny coral": 1},
"drab maroon": {"light white": 2, "vibrant turquoise": 2, "vibrant cyan": 2},
"pale maroon": {"dim red": 3},
"plaid gold": {"posh bronze": 4},
"striped coral": {"drab blue": 5, "muted bronze": 3},
"drab fuchsia": {"shiny bronze": 1},
"light cyan": {"dotted fuchsia": 1, "drab violet": 1},
"plaid silver": {"clear gray": 3, "light teal": 5, "vibrant tan": 3, "bright white": 1},
"wavy coral": {"shiny black": 1, "mirrored maroon": 3},
"posh gold": {"bright yellow": 3, "dark lavender": 2},
"drab beige": {"bright gray": 5, "pale olive": 3, "plaid chartreuse": 3},
"wavy salmon": {"shiny beige": 5, "posh violet": 1},
"pale fuchsia": {"wavy gray": 4, "wavy beige": 1},
"dim fuchsia": {"dim beige": 1, "muted cyan": 4, "clear lavender": 1},
"bright tan": {"drab crimson": 2},
"striped red": {"muted black": 2},
"dark green": {"plaid red": 5},
"faded gold": {"muted white": 2, "clear yellow": 5, "light fuchsia": 1, "dotted violet": 4},
"striped cyan": {"drab purple": 2, "shiny fuchsia": 1, "light salmon": 2},
"dull bronze": {"faded black": 1, "dull lavender": 4},
"dull cyan": {"faded salmon": 5, "clear bronze": 1},
"shiny plum": {"dark silver": 2},
"mirrored beige": {"posh red": 3, "clear chartreuse": 1, "muted magenta": 2},
"mirrored tomato": {"posh lavender": 3, "light violet": 4, "wavy crimson": 1, "dim tan": 1},
"light plum": {"dim tan": 5, "dotted beige": 2, "posh blue": 4, "light green": 4},
"mirrored blue": {"faded lavender": 4, "pale salmon": 4},
"clear maroon": {"dark salmon": 3, "shiny brown": 2, "wavy purple": 4, "plaid yellow": 1},
"bright maroon": {"pale turquoise": 4, "drab violet": 4, "clear lime": 2},
"plaid red": {"drab turquoise": 1, "striped teal": 1, "plaid yellow": 4},
"mirrored turquoise": {"clear orange": 3, "bright blue": 5, "posh plum": 3},
"dark brown": {"striped fuchsia": 5, "mirrored plum": 5, "wavy crimson": 1, "clear gray": 4},
"muted silver": {"dim tan": 2, "muted crimson": 2},
"dark red": {"wavy beige": 2, "clear bronze": 1, "shiny coral": 5, "shiny indigo": 3},
"dark tomato": {"faded gray": 2, "dim tomato": 2},
"muted blue": {"posh silver": 5},
"wavy magenta": {"faded tomato": 4},
"plaid violet": {"dim aqua": 5, "drab orange": 4, "posh lavender": 4, "dull yellow": 2},
"faded purple": {"vibrant bronze": 4, "bright bronze": 5, "faded red": 1, "clear tan": 4},
"wavy chartreuse": {"bright white": 5, "shiny coral": 2, "bright cyan": 3},
"plaid indigo": {"pale purple": 3, "posh orange": 2},
"bright tomato": {"plaid blue": 5, "posh orange": 2, "vibrant purple": 1},
"wavy maroon": {"striped white": 1},
"bright lavender": {"faded salmon": 3, "mirrored maroon": 5, "posh tomato": 5},
"light orange": {"bright blue": 2, "dark yellow": 1, "clear gray": 2, "striped salmon": 2},
"posh beige": {"dark orange": 2},
"clear chartreuse": {"striped maroon": 5, "light chartreuse": 5, "drab black": 4},
"dotted blue": {"clear cyan": 4},
"dotted coral": {"shiny tomato": 4, "posh gold": 1, "muted olive": 5},
"striped yellow": {"faded purple": 5, "drab purple": 4, "dark yellow": 5, "muted red": 5},
"dull gold": {"light turquoise": 1},
"dotted maroon": {"dark maroon": 3, "faded yellow": 2},
"clear yellow": {"plaid maroon": 2, "bright gray": 5, "pale olive": 4, "shiny indigo": 5},
"clear crimson": {"faded yellow": 5},
"dotted bronze": {"muted tomato": 2}};
try{module.exports = bagsColorRules;} catch(e){}
